# ID : GO_STP_11068


# Assignment/Task 4

Question on Numpy-

1. Import the numpy package under the name np and Print the numpy version and the configuration 

In [1]:
import numpy as np
print(np.__version__)
print(np.__config__)

1.18.1
<module 'numpy.__config__' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\__config__.py'>


2. Create a null vector of size 10

In [2]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create Simple 1-D array and check type and check data types in array

In [3]:
a = np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))
print(a.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int32


4. How to find number of dimensions, bytes per element and bytes of memory used?

In [4]:
# import sys
a = np.array([1, 2, 3, 4, 5])
print(a.ndim)
print(a.itemsize)
print(a.size)
print(a.size*a.itemsize)

1
4
5
20


5. Create a null vector of size 10 but the fifth value which is 1

In [5]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

6. Create a vector with values ranging from 10 to 49

In [6]:
a = np.arange(10, 50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

7. Reverse a vector (first element becomes last)

In [7]:
a = np.arange(10)
print(f"Original vector: {a}")
print(f"Reverse of vector: {a[::-1]}")

Original vector: [0 1 2 3 4 5 6 7 8 9]
Reverse of vector: [9 8 7 6 5 4 3 2 1 0]


8. Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
a = np.arange(9)
print(a.reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


9. Find indices of non-zero elements from [1,2,0,0,4,0]

In [9]:
a = np.array([1,2,0,0,4,0])
np.where(a!=0)

(array([0, 1, 4], dtype=int64),)

10. Create a 3x3 identity matrix

In [10]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


11. Create a 3x3x3 array with random values

In [12]:
import random

a = np.random.random((3,3,3))
a

array([[[0.26968026, 0.50574536, 0.26752136],
        [0.93461037, 0.51623604, 0.35911197],
        [0.34667409, 0.31965737, 0.80725894]],

       [[0.34580455, 0.91633797, 0.40796484],
        [0.38274672, 0.84610932, 0.58581958],
        [0.46420637, 0.41876918, 0.54169911]],

       [[0.22361167, 0.85255047, 0.71002673],
        [0.87702936, 0.48080638, 0.88916868],
        [0.23171284, 0.77392313, 0.55072222]]])

12. Create a 10x10 array with random values and find the minimum and maximum values

In [13]:
import random
a = np.random.random((10,10))
print(a)
print(f"Maximum value: {a.max()} \nMinimum value: {a.min()}")

[[0.35453476 0.24616627 0.02287666 0.69299456 0.95395328 0.92541932
  0.50535024 0.65724383 0.37699728 0.12186795]
 [0.21385658 0.53243283 0.87670133 0.42071399 0.46826269 0.44888598
  0.80594684 0.65580217 0.44645688 0.54534003]
 [0.3130684  0.13902219 0.29461845 0.64909552 0.2195401  0.7926637
  0.23327304 0.86169722 0.47904544 0.68444657]
 [0.90185483 0.54250333 0.08047799 0.31832721 0.49866458 0.14955347
  0.00427006 0.50279615 0.6391077  0.63013498]
 [0.54772024 0.3938548  0.2660164  0.53978087 0.1720643  0.51536932
  0.7222187  0.51256888 0.90959989 0.77869239]
 [0.58026192 0.52895041 0.29174192 0.94133237 0.49967512 0.0242307
  0.13860286 0.66470495 0.42432879 0.73830532]
 [0.60623303 0.35385013 0.39466469 0.05920096 0.80330877 0.12826406
  0.37893743 0.45645274 0.24741182 0.60419164]
 [0.58636603 0.56422281 0.06359022 0.67899791 0.37410007 0.34024071
  0.9192628  0.17161831 0.94307967 0.54698328]
 [0.50179727 0.49193906 0.73847056 0.04214791 0.43965233 0.10421497
  0.36232046 0

13. Create a random vector of size 30 and find the mean value

In [14]:
import random
a = np.random.random(30)
print(a)
print(f"Mean: {a.mean()}")

[0.55031681 0.27576009 0.54444712 0.55586246 0.93119429 0.54035743
 0.23018868 0.68975287 0.79904013 0.77080723 0.57295429 0.18862156
 0.4473611  0.54982863 0.49354872 0.29965786 0.73880818 0.09335951
 0.21048543 0.88249206 0.9948208  0.67601753 0.54242345 0.07775966
 0.89605754 0.09521063 0.35803255 0.69765943 0.43019451 0.84246756]
Mean: 0.5325162699342745


14 . Create a 2d array with 1 on the border and 0 inside

In [15]:
a = np.ones((5,6))
print(f"Original matrix:\n {a}")
a[1:-1,1:-1] = 0
print(f"\nMatrix after modification:\n {a}")

Original matrix:
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]

Matrix after modification:
 [[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


15. How to add a border (filled with 0's) around an existing array? 

In [16]:
import numpy as np
a = np.ones((3,3))
print(a,"\n\n")
a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 


[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


# 16. How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?    
Example -
[[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]  

Get 13, get first row only, get 3rd column only, get [2, 4, 6], replace 13 by 20

In [17]:
a = [[1, 2, 3, 4, 5, 6, 7],[8, 9, 10, 11, 12, 13, 14]]
a[1][5] = 20
a

[[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 20, 14]]

17. How to Convert a 1D array to a 2D array with 2 rows

In [18]:
a = np.arange(10)
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Create the following pattern without hardcoding. Use only numpy functions and the below input array a.  
Input:

a = np.array([1,2,3])`

Desired Output:

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [19]:
a = np.array([1,2,3])
a = np.append(np.repeat(a,3),np.tile(a,3))
a

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

19.Write a program to show how Numpy taking less memory compared to Python List?

In [20]:
import sys
l=[i for i in range(1000)]
print("for list:",sys.getsizeof(10)*len(l))
arr=np.arange(1000)
print("for nparray:",arr.itemsize*len(arr))
arr[0]

for list: 28000
for nparray: 4000


0

20. Write a program to show how Numpy taking less time compared to Python List?

In [21]:
import time

size = 1000000  
list1 = range(size)
list2 = range(size)
array1 = np.arange(size)  
array2 = np.arange(size)

initialTime = time.time()
resultantList = [(a * b) for a, b in zip(list1, list2)]
print("Time taken by Lists to perform multiplication:",(time.time() - initialTime),"seconds")

initialTime = time.time()
resultantArray = array1 * array2
print("Time taken by NumPy Arrays to perform multiplication:",(time.time() - initialTime),"seconds")

Time taken by Lists to perform multiplication: 0.11074638366699219 seconds
Time taken by NumPy Arrays to perform multiplication: 0.0019519329071044922 seconds
